### ISSUE TITLE
Define use case for Prototype A

### ISSUE THREAD

**Issue by ajRiverav** [htarridopicart/Apagon#6]
@htarridopicart , who is in PR, has had conversations with people interested in this tool and willing to donate funds. They need the following:

- better understanding of the use case given the current comms situtation (assume no data on cellphones and that SMS txts work reliably, and that data consumers do have internet and can look at the outage reports). 
- time to complete a prototype.
- costs associated with the prototype and as it scales up. 

To identify costs, we need to identify the tech stack to be used. To decided on the tech stack, we need to define the use case for the prototype A. 

The discussion will happen [here](https://goo.gl/jcQNuj), and will be posted here once it is completed.

**Comment by htarridopicart** [comment]
Updated text. It now includes how the problem is framed around existing conditions for the AEE and it includes answers to strategic questions we have been asked from stakeholders.

**Comment by ajRiverav** [comment]
Ok. I will remove the doc from being publicly accessible, and move the relevant content here.

**Comment by ajRiverav** [comment]
Prototype Alpha use case is:

1) User sends its address via sms text to a number. The address must have USPS-type format. 
2) The server receives (via a HTTP POST) this message. 
3) The server saves the sender's number and address on a database
4) The data is passed in to MapBox geocoder and plot it on MapBox Map.
