### ISSUE TITLE
Update license

### ISSUE THREAD

**Issue by ajRiverav** [htarridopicart/Apagon#7]
Make sure current contributors agree that the current license is what we want

@htarridopicart 
@Chonguis 
@Jpadilla1

**Comment by htarridopicart** [comment]
If Jesir is right about the GPL 3 License and it addresses the concerns curtailing 3rd party commercialization of the app, then I think am ok with the current license.

**Comment by ajRiverav** [comment]
Got it. It does say that if somebody uses it, it has to use it under the same conditions (i.e. make source code, including modified code, available). 
Will close it.
